#version: "2.1"
services:
  gluetun:
    image: qmcgaw/gluetun:v3
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - ${gluetun_http}:8888/tcp # HTTP proxy
      - ${gluetun_tcp_udp}:8388/tcp # Shadowsocks
      - ${gluetun_tcp_udp}:8388/udp # Shadowsocks
#      - ${gluetun_sabnzbd}:8080 #sabnzbd
      - ${gluetun_qbittorent_ui}:8082 #qbittorent
      - ${gluetun_qbittorent_tcp_udp}:6881 #qbittorent
      - ${gluetun_qbittorent_tcp_udp}:6881/udp #qbittorent
    volumes:
      - ${appdata}/gluetun:/gluetun
    environment:
      # See https://github.com/qdm12/gluetun-wiki
      - TZ=${TZ}
      - VPN_SERVICE_PROVIDER=${VPN_SERVICE_PROVIDER}
      - OPENVPN_USER=${OPENVPN_USER}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
      - SERVER_COUNTRIES=${SERVER_COUNTRIES}
    restart: unless-stopped
    networks:
      - dockernet

#  sabnzbd:
#    image: lscr.io/linuxserver/sabnzbd:latest
#    container_name: sabnzbd
#    environment:
#      - PUID=${PUID}
#      - PGID=${PGID}
#      - TZ=${TZ}
#    volumes:
#      - ${appdata}/sabnzbd:/config
#      - ${download_folder}:/downloads
#    #   ports:         # moved to gluetun
#    #     - 8080:8080
#    restart: unless-stopped
#    depends_on:
#      gluetun:
#        condition: service_healthy
#    network_mode: service:gluetun

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - WEBUI_PORT=${gluetun_qbittorent_ui}
    volumes:
      - ${appdata}/qbittorent:/config
      - ${download_folder}:/downloads
    #    ports:
    #     - 8080:8080
    #     - 6881:6881
    #     - 6881:6881/udp
    restart: unless-stopped
    depends_on:
      gluetun:
        condition: service_healthy
    network_mode: service:gluetun


networks:
  dockernet:
    external: true
